### ISSUE TITLE
[1.16.5] can't open/create a world after quiting a other

### ISSUE THREAD

**Issue by MSandro** [kyrptonaught/DatapackPortals#3]
The mod works fine, my Portals are working fine. but after I leafe a single player world and try to join it again, or a other, it doesn't work. I find this in the log:
```
[15:58:14] [main/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access field net.kyrptonaught.customportalapi.CustomPortalApiRegistry.portals from class net.kyrptonaught.datapackportals.DatapackPortalsMod
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1887) ~[?:1.8.0_51]
	at net.minecraft.class_310.method_29604(class_310.java:1959) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:1808) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_310.method_29607(class_310.java:1752) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_525.method_2736(class_525.java:298) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_525.method_19922(class_525.java:238) [intermediary-1.16.5.jar:?]
```
Hope this can be fixed.

**Comment by kyrptonaught** [comment]
1.0.3 was uploaded to curse with a fix for this
